CREATE DATABASE QLST_22520859
USE QLST_22520859
GO

CREATE TABLE KHACHHANG
(
    MAKH CHAR(5),
    TENKH VARCHAR(30),
    CONSTRAINT PK_KHACHHANG PRIMARY KEY(MAKH)
)

CREATE TABLE NHANVIEN
(
	MANV CHAR(5),
    TENNHANVEN VARCHAR(30),
	CONSTRAINT PK_NHANVIEN PRIMARY KEY(MANV),
)

CREATE TABLE SANPHAM
(
	MASP CHAR(14),
	TENSP VARCHAR(50),
	GIA MONEY
	CONSTRAINT PK_SANPHAM PRIMARY KEY(MASP)
)

CREATE TABLE CTHD
(
	SOHD CHAR(10),
	MASP CHAR(14),
	SL NUMERIC(10,3),
	THUE SMALLINT,
	CONSTRAINT PK_CTHD PRIMARY KEY(SOHD,MASP),
)

CREATE TABLE PHIEUMUA
(
    SOHD CHAR(10),
    MAKH CHAR(5),
    NGAYMUA SMALLDATETIME,
    QUAY SMALLINT,
    MANV CHAR(5),
    THANHTOAN MONEY,
    CONSTRAINT PK_PHIEUMUA PRIMARY KEY(SOHD, MAKH),
);

ALTER TABLE CTHD
ADD CONSTRAINT FK_CTHD_SANPHAM FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP);

ALTER TABLE PHIEUMUA
ADD CONSTRAINT FK_PHIEUMUA_KHACHHANG FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH);

ALTER TABLE PHIEUMUA
ADD CONSTRAINT FK_PHIEUMUA_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV);

ALTER TABLE KHACHHANG ADD DIEMTHUONG INT
ALTER TABLE SANPHAM ADD NHAMAYSX VARCHAR(10)
----CÂU 2
ALTER TABLE CTHD ADD CONSTRAINT CK_SL CHECK (SL > 0)
----CÂU 3

--PHIẾU MUA THÊM VÀ SỬA (THÀNH TIỀN)
--SẢN PHẨM SỬA (GIÁ)
-- THÀNH TIỀN PHẢI BẢNG TỔNG SẢN PHẨM MÀ KHÁCH ĐÓ ĐÃ MUA
CREATE TRIGGER TRG_THANHTOAN ON PHIEUMUA FOR INSERT,UPDATE AS
BEGIN 
	IF ( SELECT SUM(GIA)
	FROM INSERTED I, CTHD CT, SANPHAM SP
	WHERE I.SOHD = CT.SOHD AND SP.MASP = CT.MASP ) <>
	(SELECT THANHTOAN
	FROM PHIEUMUA
	WHERE SOHD = (SELECT SOHD FROM INSERTED))
	BEGIN
		PRINT 'THANHTIEN PHAI BANG TONG GIA CUA CAC SAN PHAM DA MUA'
		ROLLBACK TRANSACTION
	END
END
---CÂU 4
SELECT KH.MAKH,TENKH
FROM KHACHHANG KH, PHIEUMUA PM, CTHD CT,SANPHAM SP
WHERE KH.MAKH = PM.MAKH AND CT.SOHD  = PM.SOHD AND SP.MASP = CT.MASP
AND (TENSP LIKE 'C%' OR TENSP LIKE '%kẹo%')
--- CÂU 5
SELECT TOP 10 TENSP, COUNT(*) AS 'SO LUONG DA BAN'
FROM SANPHAM SP,CTHD CT,PHIEUMUA PM
WHERE SP.MASP = CT.MASP AND CT.SOHD  = PM.SOHD
AND YEAR(NGAYMUA) =2023
GROUP BY TENSP
ORDER BY COUNT(*) DESC
---CÂU 6
SELECT TOP 1 WITH TIES TENKH, SUM(THANHTOAN) AS 'SO TIEN DA THANH TOAN'
FROM KHACHHANG KH,PHIEUMUA PM
WHERE KH.MAKH = PM.MAKH
AND YEAR(NGAYMUA) =2023
GROUP BY TENKH
ORDER BY SUM(THANHTOAN) DESC
---CÂU 7

UPDATE KHACHHANG SET DIEMTHUONG = 100*(SELECT THANHTOAN FROM PHIEUMUA WHERE MAKH = KHACHHANG.MAKH) / 1000000 WHERE (SELECT THANHTOAN FROM PHIEUMUA WHERE MAKH = KHACHHANG.MAKH) BETWEEN 0 AND 20000000
UPDATE KHACHHANG SET DIEMTHUONG = 110*(SELECT THANHTOAN FROM PHIEUMUA WHERE MAKH = KHACHHANG.MAKH) / 1000000 WHERE (SELECT THANHTOAN FROM PHIEUMUA WHERE MAKH = KHACHHANG.MAKH) > 20000000

---CÂU 8
SELECT TOP 3 MAKH, TENKH
FROM KHACHHANG
ORDER BY DIEMTHUONG DESC

---CÂU 9
SELECT MAKH,TENKH
FROM KHACHHANG KH
WHERE NOT EXISTS
	(SELECT *
	FROM SANPHAM SP
	WHERE NHAMAYSX = 'OMO'
	AND NOT EXISTS
		(SELECT *
		FROM CTHD CT, PHIEUMUA PM
		WHERE KH.MAKH = PM.MAKH 
AND CT.SOHD  = PM.SOHD 
AND SP.MASP = CT.MASP))