use QLBH
/*Phan I */
create table KHACHHANG(
	MAKH CHAR(4) NOT NULL,
	HOTEN VARCHAR(40),
	DCHI VARCHAR(50),
	SODT VARCHAR(20),
	NGSINH SMALLDATETIME,
	DOANHSO MONEY,
	NGDK SMALLDATETIME,
	CONSTRAINT Pk_kh PRIMARY KEY (MAKH), 
);

create table NHANVIEN(
	MANV CHAR(4) NOT NULL,
	HOTEN VARCHAR(40),
	SODT VARCHAR(20),
	NGVL SMALLDATETIME,
	CONSTRAINT Pk_nv PRIMARY KEY (MANV),
);

create table SANPHAM(
	MASP CHAR(4) NOT NULL,
	TENSP VARCHAR(40),
	DVT VARCHAR(20),
	NUOCSX VARCHAR(40),
	GIA MONEY,
	CONSTRAINT Pk_sp PRIMARY KEY (MASP),
);

create table HOADON(
	SOHD INT NOT NULL,
	NGHD SMALLDATETIME,
	MAKH CHAR(4),
	MANV CHAR(4),
	TRIGIA MONEY,
	CONSTRAINT Pk_hd PRIMARY KEY (SOHD),
	CONSTRAINT Fk_hdkh FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
	CONSTRAINT Fk_hdnv FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
);

create table CTHD(
	SOHD INT NOT NULL,
	MASP CHAR(4) NOT NULL,
	SL INT,
	CONSTRAINT Pk_ct PRIMARY KEY (SOHD, MASP),
	CONSTRAINT Fk_cthd FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD),
	CONSTRAINT Fk_ctsp FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP),
);

alter table SANPHAM
ADD GHICHU VARCHAR(20);

ALTER TABLE KHACHHANG
ADD LOAIKH TINYINT;

ALTER TABLE SANPHAM
ALTER COLUMN GHICHU VARCHAR(100);

ALTER TABLE SANPHAM
DROP COLUMN GHICHU;

ALTER TABLE KHACHHANG
ALTER COLUMN LOAIKH VARCHAR(30); 

ALTER TABLE SANPHAM
ADD CONSTRAINT chk_lsp CHECK (DVT IN('cay', 'hop', 'cai', 'quyen', 'chuc'));

ALTER TABLE SANPHAM
ADD CONSTRAINT chk_gia CHECK (GIA >= 500);

ALTER TABLE CTHD
ADD CONSTRAINT chk_sl CHECK (SL >= 1);

ALTER TABLE KHACHHANG
ADD CONSTRAINT chk_ndk CHECK (NGSINH < NGDK);

/* Phan II */
use QLGV

create table KHOA(
	MAKHOA VARCHAR(4) NOT NULL,
	TENKHOA VARCHAR(40),
	NGTLAP SMALLDATETIME,
	TRGKHOA CHAR(4),
	CONSTRAINT Pk_khoa PRIMARY KEY (MAKHOA),
);

create table MONHOC(
	MAMH VARCHAR(10) NOT NULL,
	TENMH VARCHAR(40),
	TCLT TINYINT,
	TCTH TINYINT,
	MAKHOA VARCHAR(4),
	CONSTRAINT Pk_mh PRIMARY KEY (MAMH),
	CONSTRAINT Fk_mhk FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA), 
);

create table DIEUKHIEN(
	MAMH VARCHAR(10) NOT NULL,
	MAMH_TRUOC VARCHAR(10) NOT NULL,
	CONSTRAINT Pk_dk PRIMARY KEY (MAMH, MAMH_TRUOC),
	CONSTRAINT Fk_dkmh FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH),
	CONSTRAINT Fk_dkmhT FOREIGN KEY (MAMH_TRUOC) REFERENCES MONHOC(MAMH),  
	CONSTRAINT ck_dkm CHECK(MAMH != MAMH_TRUOC),
);

create table GIAOVIEN(
	MAGV CHAR(4) NOT NULL,
	HOTEN VARCHAR(40),
	HOCVI VARCHAR(10),
	HOCHAM VARCHAR(10),
	GIOITINH VARCHAR(3),
	NGSINH SMALLDATETIME,
	NGVL SMALLDATETIME,
	HESO NUMERIC(4,2),
	MUCLUONG MONEY,
	MAKHOA VARCHAR(4),
	CONSTRAINT Pk_gv PRIMARY KEY (MAGV),
	CONSTRAINT Fk_gvk FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA),
);

create table LOP(
	MALOP CHAR(3) NOT NULL,
	TENLOP VARCHAR(40),
	TRGLOP CHAR(5),
	SISO TINYINT,
	MAGVCN CHAR(4),
	CONSTRAINT Pk_lop PRIMARY KEY (MALOP),
	CONSTRAINT Fk_lopgv FOREIGN KEY (MAGVCN) REFERENCES GIAOVIEN(MAGV),
);

create table HOCVIEN(
	MAHV CHAR(5) NOT NULL,
	HO VARCHAR(40),
	TEN VARCHAR(10),
	NGSINH SMALLDATETIME,
	GIOITINH VARCHAR(3),
	NOISINH VARCHAR(40),
	MALOP CHAR(3),
	CONSTRAINT Pk_hv PRIMARY KEY (MAHV),
	CONSTRAINT Fk_hvl FOREIGN KEY (MALOP) REFERENCES LOP(MALOP),
);

create table GIANGDAY(
	MALOP CHAR(3) NOT NULL,
	MAMH VARCHAR(10) NOT NULL,
	MAGV CHAR(4),
	HOCKY TINYINT,
	NAM SMALLINT,
	TUNGAY SMALLDATETIME,
	DENNGAY SMALLDATETIME,
	CONSTRAINT Pk_gd PRIMARY KEY (MALOP,MAMH,MAGV),
	CONSTRAINT Fk_gdl FOREIGN KEY (MALOP) REFERENCES LOP(MALOP),
	CONSTRAINT Fk_gdmh FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH),
	CONSTRAINT Fk_gdgv FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV),
);

create table KETQUATHI(
	MAHV CHAR(5) NOT NULL,
	MAMH VARCHAR(10) NOT NULL,
	LANTHI TINYINT NOT NULL,
	NGTHI SMALLDATETIME,
	DIEM NUMERIC(4,2),
	KQUA VARCHAR(10),
	CONSTRAINT Pk_kqt PRIMARY KEY (MAHV,MAMH,LANTHI),
	CONSTRAINT Fk_kqthv FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV),
	CONSTRAINT Fk_kqtmh FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH),
);

ALTER TABLE LOP
ADD CONSTRAINT Fk_loptl FOREIGN KEY (TRGLOP) REFERENCES HOCVIEN(MAHV);

ALTER TABLE HOCVIEN
ADD GHICHU VARCHAR(40);

ALTER TABLE HOCVIEN
ADD DIEMTB SMALLINT;

ALTER TABLE HOCVIEN
ADD XEPLOAI CHAR(5);
